language: ruby
rvm:
  - 1.9.3
  - 1.9.2

services: mysql

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database munkiserver;'

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
