web:
  build: .
  ports:
    - "3000:3000"
  links:
    - redis
    - mysql
redis:
  image: redis:3
mysql:
  image: mysql:5.7
  environment:
    - MYSQL_DATABASE=munkiserver
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=munkiserver
    - MYSQL_PASSWORD=munkiserver
