web:
  build: .
  environment:
    - DATABASE_URL=mysql2://munkiserver:munkiserver@mysql:3306/munkiserver
  ports:
    - "3000"
  links:
    - redis
    - mysql
redis:
  image: redis:3
mysql:
  image: mysql:5.7
  environment:
    - MYSQL_DATABASE=munkiserver
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=munkiserver
    - MYSQL_PASSWORD=munkiserver
nginx:
  image: munkiserver/nginx:latest
  ports:
    - "8080:80"
  links:
    - web
